/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fpt.ptcd.ui.panel;

import com.fpt.ptcd.util.RoundedButton;
import com.fpt.ptcd.dao.BillDAO;
import com.fpt.ptcd.dao.BillDetailsDAO;
import com.fpt.ptcd.entity.Bill;
import com.fpt.ptcd.entity.BillDetails;
import com.fpt.ptcd.ui.add.BillManagerAddJDialog;
import com.fpt.ptcd.ui.update.BillManagerUpdateJDialog;
import com.fpt.ptcd.util.MsgBox;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class BillManagerJPannel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryJPannel
     */
    public BillManagerJPannel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BillManager = new javax.swing.JScrollPane();
        tblBillManager = new javax.swing.JTable();
        btnLast = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnSelectAll = new RoundedButton("", 20);
        btnUnSelectAll = new RoundedButton("", 20);
        jPanel6 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        cboCategory = new javax.swing.JComboBox<>();
        dcBegin = new com.toedter.calendar.JDateChooser();
        dcEnd = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        btnAdd = new RoundedButton("", 20);
        btnUpdate = new RoundedButton("", 20);
        btnDelete = new RoundedButton("", 20);

        setPreferredSize(new java.awt.Dimension(960, 680));

        BillManager.setBackground(new java.awt.Color(255, 255, 255));
        BillManager.setForeground(new java.awt.Color(255, 255, 255));

        tblBillManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã số", "Thẻ số", "Thời điểm tạo", "Thời điểm thanh toán", "Số lượng", "Trạng thái", "Chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BillManager.setViewportView(tblBillManager);

        btnLast.setBackground(new java.awt.Color(51, 51, 51));
        btnLast.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText("<<");
        btnLast.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(51, 51, 51));
        btnPrevious.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("<");
        btnPrevious.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(51, 51, 51));
        btnFirst.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText(">>");
        btnFirst.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(51, 51, 51));
        btnNext.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText(">");
        btnNext.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSelectAll.setBackground(new java.awt.Color(242, 242, 242));
        btnSelectAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/SelectAll.png"))); // NOI18N
        btnSelectAll.setText("Chọn tất cả");
        btnSelectAll.setBorder(null);
        btnSelectAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelectAll.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSelectAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        btnUnSelectAll.setBackground(new java.awt.Color(242, 242, 242));
        btnUnSelectAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/UnSelectAll.png"))); // NOI18N
        btnUnSelectAll.setText("Bỏ chọn tất cả");
        btnUnSelectAll.setBorder(null);
        btnUnSelectAll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUnSelectAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUnSelectAll.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUnSelectAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnSelectAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUnSelectAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUnSelectAll))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSearch.setText("Tìm kiếm");

        cboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAdd.setBackground(new java.awt.Color(242, 242, 242));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/save.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setBorder(null);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(242, 242, 242));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setBorder(null);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(242, 242, 242));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/delete (1).png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setBorder(null);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BillManager, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BillManager, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.moveLast();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        this.movePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.moveFirst();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.moveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        // TODO add your handling code here:
        this.selectAll();
    }//GEN-LAST:event_btnSelectAllActionPerformed

    private void btnUnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnSelectAllActionPerformed
        // TODO add your handling code here:
        this.deselectAll();
    }//GEN-LAST:event_btnUnSelectAllActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.insertBill();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.updateBill();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        this.deleteBill();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane BillManager;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JButton btnUnSelectAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboCategory;
    private com.toedter.calendar.JDateChooser dcBegin;
    private com.toedter.calendar.JDateChooser dcEnd;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTable tblBillManager;
    // End of variables declaration//GEN-END:variables
 // ======================== DAO ==========================
    private final BillDAO billDAO = new BillDAO();
    private final BillDetailsDAO billDetailDAO = new BillDetailsDAO();

// ======================== KHỞI TẠO ==========================
    private void init() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Mã số", "Thẻ phiếu", "Thời điểm tại", "Thời điểm thanh toán", "Loại hình thanh toán", "Trạng thái", "Chọn"}, 0) {

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 6 ? Boolean.class : String.class; // Cột cuối là checkbox
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 6; // Chỉ cho tick chọn ở cột cuối
            }
        };
        tblBillManager.setModel(model);
        fillTable(); // nạp bảng ban đầu
    }

// ======================== ĐỔ DỮ LIỆU VÀO BẢNG ==========================
    private void fillTable() {
        List<Bill> list = billDAO.selectAll(); // sau này có thể lọc theo ngày, category...
        DefaultTableModel model = (DefaultTableModel) tblBillManager.getModel();
        model.setRowCount(0);
        try {
            for (Bill b : list) {
                model.addRow(new Object[]{
                    b.getId(),
                    b.getCardId() != null ? b.getCardId().toString() : "",
                    formatDate(b.getCheckIn()),
                    formatDate(b.getCheckOut()),
                    getPaymentMethodText(b.getPaymentMethod()),
                    b.getStatus() ? "Đã thanh toán" : "Chưa thanh toán",
                    false
                });
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy cập dữ liệu: " + e.getMessage());
        }
    }

// ======================== THÊM HÓA ĐƠN ==========================
    private void insertBill() {
        BillManagerAddJDialog dialog = new BillManagerAddJDialog(null, true);
        dialog.setVisible(true);

        if (dialog.isConfirmed()) {
            Bill bill = dialog.getBill();
            List<BillDetails> details = dialog.getBillDetails();

            if (bill != null && details != null) {
                try {
                    billDAO.insert(bill);
                    for (BillDetails d : details) {
                        billDetailDAO.insert(d);
                    }
                    MsgBox.alert(this, "Thêm hóa đơn thành công!");
                    fillTable();
                } catch (Exception e) {
                    MsgBox.alert(this, "Lỗi khi thêm hóa đơn: " + e.getMessage());
                }
            }
        }
    }

// ======================== CẬP NHẬT HÓA ĐƠN ==========================
    private void updateBill() {
        int row = tblBillManager.getSelectedRow();
        if (row == -1) {
            MsgBox.alert(this, "Vui lòng chọn một hóa đơn để cập nhật.");
            return;
        }

        int billId = Integer.parseInt(tblBillManager.getValueAt(row, 0).toString());
        Bill bill = billDAO.selectByID(billId);
        List<BillDetails> details = billDetailDAO.selectByBillId(billId);

        if (bill == null || details.isEmpty()) {
            MsgBox.alert(this, "Không tìm thấy dữ liệu hóa đơn.");
            return;
        }

        BillManagerUpdateJDialog dialog = new BillManagerUpdateJDialog(null, true);
        dialog.setForm(bill, details);
        dialog.setVisible(true);

        if (dialog.isConfirmed()) {
            Bill updatedBill = dialog.getBill();
            List<BillDetails> updatedDetails = dialog.getBillDetails();

            if (updatedBill != null && updatedDetails != null) {
                try {
                    billDAO.update(updatedBill);
                    billDetailDAO.delete(updatedBill.getId());
                    for (BillDetails d : updatedDetails) {
                        billDetailDAO.insert(d);
                    }
                    MsgBox.alert(this, "Cập nhật hóa đơn thành công!");
                    fillTable();
                } catch (Exception e) {
                    MsgBox.alert(this, "Lỗi khi cập nhật hóa đơn: " + e.getMessage());
                }
            }
        }
    }

// ======================== XÓA HÓA ĐƠN ==========================
    private void deleteBill() {
        if (!MsgBox.confirm(this, "Bạn có chắc muốn xóa các hóa đơn đã chọn?")) {
            return;
        }

        boolean deletedAny = false;
        DefaultTableModel model = (DefaultTableModel) tblBillManager.getModel();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            Boolean selected = (Boolean) model.getValueAt(i, 6);
            if (Boolean.TRUE.equals(selected)) {
                int id = Integer.parseInt(model.getValueAt(i, 0).toString());
                try {
                    billDetailDAO.delete(id);
                    billDAO.delete(id);
                    deletedAny = true;
                } catch (Exception e) {
                    MsgBox.alert(this, "Lỗi xóa ID " + id + ": " + e.getMessage());
                }
            }
        }

        MsgBox.alert(this, deletedAny ? "Xóa thành công." : "Không có hóa đơn nào được chọn.");
        fillTable();
    }

// ======================== HỖ TRỢ ==========================
    private String formatDate(Date date) {
        return date == null ? "" : new SimpleDateFormat("dd/MM/yyyy").format(date);
    }

    private String getPaymentMethodText(Integer method) {
        return switch (method) {
            case 1 ->
                "Tiền mặt";
            case 2 ->
                "Chuyển khoản";
            default ->
                "Khác";
        };
    }
    
    
    private void selectAll() {
        for (int i = 0; i < tblBillManager.getRowCount(); i++) {
            tblBillManager.setValueAt(true, i, 6);
        }
    }

    private void deselectAll() {
        for (int i = 0; i < tblBillManager.getRowCount(); i++) {
            tblBillManager.setValueAt(false, i, 6);
        }
    }

    private void moveFirst() {
        moveTo(0);
    }

    private void movePrevious() {
        moveTo(tblBillManager.getSelectedRow() - 1);
    }

    private void moveNext() {
        moveTo(tblBillManager.getSelectedRow() + 1);
    }

    private void moveLast() {
        moveTo(tblBillManager.getRowCount() - 1);
    }

    private void moveTo(int index) {
        int rowCount = tblBillManager.getRowCount();
        if (rowCount == 0) {
            return;
        }

        if (index < 0) {
            index = rowCount - 1;
        }
        if (index >= rowCount) {
            index = 0;
        }

        tblBillManager.clearSelection();
        tblBillManager.setRowSelectionInterval(index, index);
    }

}
