/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fpt.ptcd.ui.panel;

import com.fpt.ptcd.dao.MaterialDAO;
import com.fpt.ptcd.dao.MaterialTypeDAO;
import com.fpt.ptcd.entity.Material;
import com.fpt.ptcd.entity.MaterialType;
import com.fpt.ptcd.ui.update.MaterialManagerAddJDialog;
import com.fpt.ptcd.util.MsgBox;
import com.fpt.ptcd.util.RoundedButton;
import com.fpt.ptcd.util.XImage;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class MaterialManagerJPannel extends javax.swing.JPanel {

    /**
     * Creates new form HistoryJPannel
     */
    public MaterialManagerJPannel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        History = new javax.swing.JScrollPane();
        tblMaterialManager = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnSelectAll = new RoundedButton("", 20);
        btnDeSelectAll = new RoundedButton("", 20);
        jPanel5 = new javax.swing.JPanel();
        btnAdd = new RoundedButton("", 20);
        btnUpdate = new RoundedButton("", 20);
        btnDelete = new RoundedButton("", 20);
        jPanel6 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtNameSeatch = new javax.swing.JTextField();
        cboDateSearch = new javax.swing.JComboBox<>();
        btnLast = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        cboMaterialType = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(960, 680));

        History.setBackground(new java.awt.Color(255, 255, 255));
        History.setForeground(new java.awt.Color(255, 255, 255));

        tblMaterialManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã số", "Tên", "Số lượng", "Nguồn nhập", "Ngày nhập", "Loại", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        History.setViewportView(tblMaterialManager);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSelectAll.setBackground(new java.awt.Color(242, 242, 242));
        btnSelectAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/SelectAll.png"))); // NOI18N
        btnSelectAll.setText("Chọn tất cả");
        btnSelectAll.setBorder(null);
        btnSelectAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelectAll.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSelectAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        btnDeSelectAll.setBackground(new java.awt.Color(242, 242, 242));
        btnDeSelectAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/UnSelectAll.png"))); // NOI18N
        btnDeSelectAll.setText("Bỏ chọn tất cả");
        btnDeSelectAll.setBorder(null);
        btnDeSelectAll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDeSelectAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeSelectAll.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDeSelectAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDeSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeSelectAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSelectAll, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeSelectAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeSelectAll))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAdd.setBackground(new java.awt.Color(242, 242, 242));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/save.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setBorder(null);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(242, 242, 242));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setBorder(null);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(242, 242, 242));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/cafe/icons/delete (1).png"))); // NOI18N
        btnDelete.setText("Xôá");
        btnDelete.setBorder(null);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSearch.setText("Tìm kiếm");

        txtNameSeatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameSeatchActionPerformed(evt);
            }
        });

        cboDateSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cboDateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNameSeatch, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameSeatch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDateSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        btnLast.setBackground(new java.awt.Color(51, 51, 51));
        btnLast.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText("<<");
        btnLast.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(51, 51, 51));
        btnPrevious.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("<");
        btnPrevious.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(51, 51, 51));
        btnNext.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText(">>");
        btnNext.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(51, 51, 51));
        btnFirst.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText(">");
        btnFirst.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        cboMaterialType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        lblPhoto.setText("jLabel1");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboMaterialType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(History)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(History, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboMaterialType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        // TODO add your handling code here:
        this.selectAll();
    }//GEN-LAST:event_btnSelectAllActionPerformed

    private void btnDeSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeSelectAllActionPerformed
        // TODO add your handling code here:
        this.deselectAll();
    }//GEN-LAST:event_btnDeSelectAllActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.insertBakery();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.updateBakery();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        this.deleteBakery();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtNameSeatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameSeatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameSeatchActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.moveLast();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        this.movePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.moveNext();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.moveFirst();
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane History;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeSelectAll;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboDateSearch;
    private javax.swing.JComboBox<String> cboMaterialType;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JTable tblMaterialManager;
    private javax.swing.JTextField txtNameSeatch;
    private javax.swing.JTextArea txtNote;
    // End of variables declaration//GEN-END:variables

    private final MaterialDAO dao = new MaterialDAO();
    private final MaterialTypeDAO category = new MaterialTypeDAO();
    private final Map<String, Integer> categoryMap = new HashMap<>();

    private void init() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Mã số", "Tên", "Số lượng", "Nguồn nhập", "Ngày nhập", "Loại", "Chọn"}, 0) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 6 ? Boolean.class : Object.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 6;
            }
        };
        tblMaterialManager.setModel(model);
        fillComboBoxCategory();
        fillTable();
        addTableSelectionListener();
    }

    private void fillComboBoxCategory() {
        cboMaterialType.removeAllItems();
        categoryMap.clear();

        List<MaterialType> list = category.selectAll();
        for (MaterialType mt : list) {
            cboMaterialType.addItem(mt.getName());             // Hiển thị tên
            categoryMap.put(mt.getName(), mt.getId());      // Lưu ánh xạ name → id
        }
    }

    public int getSelectedCategoryId() {
        String selectedName = (String) cboMaterialType.getSelectedItem();
        return categoryMap.getOrDefault(selectedName, -1);
    }

    public void setSelectedCategoryId(int id) {
        for (Map.Entry<String, Integer> entry : categoryMap.entrySet()) {
            if (entry.getValue() == id) {
                cboMaterialType.setSelectedItem(entry.getKey());
                break;
            }
        }
    }

    private void fillTable() {
        List<Material> list = dao.selectAll();
        DefaultTableModel model = (DefaultTableModel) tblMaterialManager.getModel();
        model.setRowCount(0);
        try {
            for (Material m : list) {
                // Lấy tên từ cboCategory đã có sẵn ComboItem
                String categoryName = "Không rõ";
                for (Map.Entry<String, Integer> entry : categoryMap.entrySet()) {
                    if (entry.getValue() == m.getMaterialID()) {
                        categoryName = entry.getKey();
                        break;
                    }
                }
                Object[] row = {
                    m.getMaterialID(),
                    m.getName(),
                    m.getQuantity(),
                    m.getSupplier(),
                    m.getImportDate(),
                    m.getTypeID(),
                    false
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi đổ dữ liệu: " + e.getMessage());
        }
    }

    private void addTableSelectionListener() {
        tblMaterialManager.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tblMaterialManager.getSelectedRow();
                if (selectedRow != -1) {
                    Object value = tblMaterialManager.getValueAt(selectedRow, 0); // Cột 0 = ID
                    if (value != null) {
                        try {
                            int id = Integer.parseInt(value.toString().trim()); // TRIM loại bỏ khoảng trắng
                            Material material = dao.selectByID(id);
                            if (material == null) {
                            } else {
                                lblName.setText(material.getName());
                                txtNote.setText(material.getNote());
                                String photo = material.getPhoto();
                                if (photo != null && !photo.isEmpty()) {
                                    lblPhoto.setIcon(XImage.readScaled(photo, lblPhoto));
                                    lblPhoto.setToolTipText(photo);
                                } else {
                                    lblPhoto.setIcon(XImage.readScaled("no_image.png", lblPhoto));
                                    lblPhoto.setToolTipText("Không có ảnh");
                                }
                            }
                        } catch (NumberFormatException ex) {
                            System.out.println("❌ Lỗi chuyển ID sang số nguyên: " + value);
                        }
                    } else {
                        System.out.println("❌ Cột ID null ở dòng " + selectedRow);
                    }
                }
            }
        });
    }

    private void insertBakery() {
        MaterialManagerAddJDialog dialog = new MaterialManagerAddJDialog(null, true);
        dialog.setTitle("Thêm sản phẩm");
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        Material material = dialog.getForm();
        if (material != null) {
            try {
                dao.insert(material);
                MsgBox.alert(this, "Thêm sản phẩm thành công!");
                fillTable();
            } catch (Exception e) {
                MsgBox.alert(this, "Lỗi khi thêm: " + e.getMessage());
            }
        }
    }

    private void updateBakery() {
        int selectedRow = tblMaterialManager.getSelectedRow();
        if (selectedRow == -1) {
            MsgBox.alert(this, "Vui lòng chọn một dòng để cập nhật!");
            return;
        }

        int id = Integer.parseInt(tblMaterialManager.getValueAt(selectedRow, 0).toString());
        Material material = dao.selectByID(id);
        if (material == null) {
            MsgBox.alert(this, "Không tìm thấy sản phẩm có ID: " + id);
            return;
        }

        MaterialManagerAddJDialog dialog = new MaterialManagerAddJDialog(null, true);
        dialog.setForm(material);
        dialog.setTitle("Cập nhật sản phẩm");
        dialog.getBtnSave().setText("Cập nhật");

        for (ActionListener al : dialog.getBtnSave().getActionListeners()) {
            dialog.getBtnSave().removeActionListener(al);
        }

        dialog.getBtnSave().addActionListener(evt -> {
            Material updated = dialog.getForm();
            if (updated != null) {
                try {
                    dao.update(updated);
                    MsgBox.alert(dialog, "Cập nhật thành công!");
                    dialog.dispose();
                    fillTable();
                } catch (Exception ex) {
                    MsgBox.alert(dialog, "Lỗi cập nhật: " + ex.getMessage());
                }
            }
        });

        dialog.setVisible(true);
    }

    private void deleteBakery() {
        if (!MsgBox.confirm(this, "Bạn chắc chắn muốn xóa các sản phẩm đã chọn?")) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblMaterialManager.getModel();
        boolean deleted = false;

        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            Boolean selected = (Boolean) model.getValueAt(i, 6);
            if (selected != null && selected) {
                int id = Integer.parseInt(model.getValueAt(i, 0).toString());
                try {
                    dao.delete(id);
                    deleted = true;
                } catch (Exception e) {
                    MsgBox.alert(this, "Lỗi xóa sản phẩm ID " + id + ": " + e.getMessage());
                }
            }
        }

        if (deleted) {
            MsgBox.alert(this, "Xóa thành công.");
            fillTable();
        } else {
            MsgBox.alert(this, "Không có sản phẩm nào được chọn.");
        }
    }

    private void selectAll() {
        for (int i = 0; i < tblMaterialManager.getRowCount(); i++) {
            tblMaterialManager.setValueAt(true, i, 6);
        }
    }

    private void deselectAll() {
        for (int i = 0; i < tblMaterialManager.getRowCount(); i++) {
            tblMaterialManager.setValueAt(false, i, 6);
        }
    }

    private void moveFirst() {
        moveTo(0);
    }

    private void movePrevious() {
        moveTo(tblMaterialManager.getSelectedRow() - 1);
    }

    private void moveNext() {
        moveTo(tblMaterialManager.getSelectedRow() + 1);
    }

    private void moveLast() {
        moveTo(tblMaterialManager.getRowCount() - 1);
    }

    private void moveTo(int index) {
        int rowCount = tblMaterialManager.getRowCount();
        if (rowCount == 0) {
            return;
        }

        if (index < 0) {
            index = rowCount - 1;
        }
        if (index >= rowCount) {
            index = 0;
        }

        tblMaterialManager.clearSelection();
        tblMaterialManager.setRowSelectionInterval(index, index);
    }

}
