/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fpt.ptcd.ui.frame;

import com.fpt.ptcd.ui.frame.BakeryController;
import com.fpt.ptcd.ui.panel.CategoryManagerJPannel;
import com.fpt.ptcd.ui.panel.RevenueManagerJPanel;
import com.fpt.ptcd.ui.panel.BakeryJPannel;
import com.fpt.ptcd.ui.panel.MaterialManagerJPannel;
import com.fpt.ptcd.ui.panel.GroundWorkJPannel;
import com.fpt.ptcd.ui.panel.BillJPannel;
import com.fpt.ptcd.ui.panel.CardManagerJPannel;
import com.fpt.ptcd.ui.panel.BakeryManagerJPannel;
//import newpackage.BillManagerJPannel;
import com.fpt.ptcd.ui.panel.HistoryJPannel;
import com.fpt.ptcd.ui.panel.UserManagerJPannel;
import com.fpt.ptcd.util.LookAndFeelUtil;
import com.fpt.ptcd.util.XAuth;
import static com.fpt.ptcd.util.XAuth.user;
import com.fpt.ptcd.util.XImage;
import com.fpt.ptcd.entity.User;
import com.fpt.ptcd.ui.dialog.LoginJDialog;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author admin
 */
public final class BakeryJFrame extends javax.swing.JFrame implements BakeryController {

    /**
     * Creates new form PolyJFrameTest
     */
    public BakeryJFrame() {
        LookAndFeelUtil.applyFlatLafLight(); // Cẩn thận gọi trước initComponents
        initComponents();
        init();
        setTitle("Quản lý tiệm bánh");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblWellcome = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnHistory = new javax.swing.JButton();
        btnBill = new javax.swing.JButton();
        btnBakery = new javax.swing.JButton();
        btnGroundWork = new javax.swing.JButton();
        btnBillManager = new javax.swing.JButton();
        btnUserManager = new javax.swing.JButton();
        btnRevenueManager = new javax.swing.JButton();
        btnCategoryManager = new javax.swing.JButton();
        btnBakeryManager = new javax.swing.JButton();
        btnMaterialManager = new javax.swing.JButton();
        btnCardManager = new javax.swing.JButton();
        menu = new javax.swing.JPanel();

        mainPanel.setBackground(new java.awt.Color(232, 232, 232));
        mainPanel.setMaximumSize(new java.awt.Dimension(0, 0));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        mainPanel.setLayout(new java.awt.CardLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1209, 680));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btnExit.setBackground(new java.awt.Color(38, 38, 38));
        btnExit.setFont(new java.awt.Font("Lato Black", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("                   THOÁT");
        btnExit.setBorder(null);
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnChangePassword.setBackground(new java.awt.Color(38, 38, 38));
        btnChangePassword.setFont(new java.awt.Font("Lato Black", 0, 12)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("                    ĐỔI MẬT KHẨU");
        btnChangePassword.setBorder(null);
        btnChangePassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("- USERNAME -");

        lblWellcome.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        lblWellcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWellcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWellcome.setText("WELLCOME");
        lblWellcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane2.setBackground(new java.awt.Color(255, 204, 0));
        jScrollPane2.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(226, 172, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHistory.setBackground(new java.awt.Color(226, 172, 0));
        btnHistory.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnHistory.setText("Lịch Sử Bán Hàng");
        btnHistory.setBorder(null);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 189, 40));

        btnBill.setBackground(new java.awt.Color(226, 172, 0));
        btnBill.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnBill.setForeground(new java.awt.Color(255, 255, 255));
        btnBill.setText("Phiếu bán hàng");
        btnBill.setBorder(null);
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 189, 40));

        btnBakery.setBackground(new java.awt.Color(226, 172, 0));
        btnBakery.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnBakery.setForeground(new java.awt.Color(255, 255, 255));
        btnBakery.setText("Sản phẩm");
        btnBakery.setBorder(null);
        btnBakery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBakeryActionPerformed(evt);
            }
        });
        jPanel1.add(btnBakery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 189, 40));

        btnGroundWork.setBackground(new java.awt.Color(226, 172, 0));
        btnGroundWork.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnGroundWork.setForeground(new java.awt.Color(255, 255, 255));
        btnGroundWork.setText("Quản lý cơ sở");
        btnGroundWork.setBorder(null);
        btnGroundWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroundWorkActionPerformed(evt);
            }
        });
        jPanel1.add(btnGroundWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 189, 40));

        btnBillManager.setBackground(new java.awt.Color(226, 172, 0));
        btnBillManager.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnBillManager.setForeground(new java.awt.Color(255, 255, 255));
        btnBillManager.setText("Quản lý phiếu");
        btnBillManager.setBorder(null);
        btnBillManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnBillManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 189, 40));

        btnUserManager.setBackground(new java.awt.Color(226, 172, 0));
        btnUserManager.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnUserManager.setForeground(new java.awt.Color(255, 255, 255));
        btnUserManager.setText("Quản lý người dùng");
        btnUserManager.setBorder(null);
        btnUserManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnUserManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 189, 40));

        btnRevenueManager.setBackground(new java.awt.Color(226, 172, 0));
        btnRevenueManager.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnRevenueManager.setForeground(new java.awt.Color(255, 255, 255));
        btnRevenueManager.setText("Quản lý doanh thu");
        btnRevenueManager.setBorder(null);
        btnRevenueManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnRevenueManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 189, 40));

        btnCategoryManager.setBackground(new java.awt.Color(226, 172, 0));
        btnCategoryManager.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnCategoryManager.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoryManager.setText("Quản lý loại sản phẩm");
        btnCategoryManager.setBorder(null);
        btnCategoryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnCategoryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 189, 40));

        btnBakeryManager.setBackground(new java.awt.Color(226, 172, 0));
        btnBakeryManager.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnBakeryManager.setForeground(new java.awt.Color(255, 255, 255));
        btnBakeryManager.setText("Quản lý sản phẩm");
        btnBakeryManager.setBorder(null);
        btnBakeryManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBakeryManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnBakeryManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 189, 40));

        btnMaterialManager.setBackground(new java.awt.Color(226, 172, 0));
        btnMaterialManager.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnMaterialManager.setForeground(new java.awt.Color(255, 255, 255));
        btnMaterialManager.setText("Quản lý nguyên liệu");
        btnMaterialManager.setBorder(null);
        btnMaterialManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaterialManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 189, 40));

        btnCardManager.setBackground(new java.awt.Color(226, 172, 0));
        btnCardManager.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        btnCardManager.setForeground(new java.awt.Color(255, 255, 255));
        btnCardManager.setText("Quản lý thẻ");
        btnCardManager.setBorder(null);
        btnCardManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardManagerActionPerformed(evt);
            }
        });
        jPanel1.add(btnCardManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 189, 40));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblWellcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWellcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 231, 680));

        menu.setPreferredSize(new java.awt.Dimension(960, 680));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 0, 960, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        this.ChangePasswordJDialog(this);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        // TODO add your handling code here:
        showPanel(new BillJPannel());
    }//GEN-LAST:event_btnBillActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        showPanel(new HistoryJPannel());
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnBakeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBakeryActionPerformed
        // TODO add your handling code here:
        showPanel(new BakeryJPannel());
    }//GEN-LAST:event_btnBakeryActionPerformed

    private void btnGroundWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroundWorkActionPerformed
        // TODO add your handling code here:
        showPanel(new GroundWorkJPannel());
    }//GEN-LAST:event_btnGroundWorkActionPerformed

    private void btnBillManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillManagerActionPerformed
        // TODO add your handling code here:
//        showPanel(new BillManagerJPannel());
    }//GEN-LAST:event_btnBillManagerActionPerformed

    private void btnUserManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagerActionPerformed
        showPanel(new UserManagerJPannel());
    }//GEN-LAST:event_btnUserManagerActionPerformed

    private void btnRevenueManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueManagerActionPerformed
        // TODO add your handling code here:
        showPanel(new RevenueManagerJPanel());
    }//GEN-LAST:event_btnRevenueManagerActionPerformed

    private void btnCategoryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryManagerActionPerformed
        // TODO add your handling code here:
        showPanel(new CategoryManagerJPannel());
    }//GEN-LAST:event_btnCategoryManagerActionPerformed

    private void btnBakeryManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBakeryManagerActionPerformed
        // TODO add your handling code here:
        showPanel(new BakeryManagerJPannel());
    }//GEN-LAST:event_btnBakeryManagerActionPerformed

    private void btnMaterialManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialManagerActionPerformed
        // TODO add your handling code here:
        showPanel(new MaterialManagerJPannel());
    }//GEN-LAST:event_btnMaterialManagerActionPerformed

    private void btnCardManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardManagerActionPerformed
        // TODO add your handling code here:
        showPanel(new CardManagerJPannel());
    }//GEN-LAST:event_btnCardManagerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loadUserInfo();
        setPermisson();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BakeryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BakeryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BakeryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BakeryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BakeryJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBakery;
    private javax.swing.JButton btnBakeryManager;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnBillManager;
    private javax.swing.JButton btnCardManager;
    private javax.swing.JButton btnCategoryManager;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGroundWork;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnMaterialManager;
    private javax.swing.JButton btnRevenueManager;
    private javax.swing.JButton btnUserManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWellcome;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
public void init() {
        this.WellcomeJDialog(this);
        if (!showLogin()) {
            System.exit(0);
        }

        menu.setLayout(new BorderLayout());
        menu.add(mainPanel, BorderLayout.CENTER);
    }

    private boolean showLogin() {
        LoginJDialog dialog = new LoginJDialog(this, true);
        dialog.setVisible(true);
        return dialog.isSucceeded(); // 🔁 kiểm tra kết quả login
    }

    private void loadUserInfo() {
        User u = XAuth.user;
        lblUsername.setText(u.getFullname());
        ImageIcon icon = XImage.readScaled(user.getPhoto(), lblProfile);
        if (icon != null) {
            lblProfile.setIcon(icon);
        } else {
            lblProfile.setIcon(new ImageIcon("src/main/resources/poly/cafe/icons/default-avatar.jpg"));
        }
    }

    private void setPermisson() {
        if (XAuth.isManager()) {
            btnBakery.setVisible(true);
            btnBakeryManager.setVisible(true);
            btnBill.setVisible(true);
            btnBillManager.setVisible(true);
            btnCardManager.setVisible(true);
            btnCategoryManager.setVisible(true);
            btnGroundWork.setVisible(true);
            btnHistory.setVisible(true);
            btnMaterialManager.setVisible(true);
            btnRevenueManager.setVisible(true);
            btnUserManager.setVisible(true);
        } else {
            btnBakery.setVisible(true);
            btnBakeryManager.setVisible(false);
            btnBill.setVisible(true);
            btnBillManager.setVisible(false);
            btnCardManager.setVisible(false);
            btnCategoryManager.setVisible(false);
            btnGroundWork.setVisible(false);
            btnHistory.setVisible(true);
            btnMaterialManager.setVisible(false);
            btnRevenueManager.setVisible(false);
            btnUserManager.setVisible(false);
        }
    }

    private void showPanel(JPanel panel) {
        mainPanel.removeAll();
        mainPanel.setLayout(new BorderLayout());
        mainPanel.add(panel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

}
