/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fpt.ptcd.ui.update;

import com.fpt.ptcd.entity.Category;
import com.fpt.ptcd.util.RoundedButton;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CategoryUpdateJDialog extends javax.swing.JDialog {

    
        private Category category;
    /**
     * Creates new form HistoryAddJDialog
     */
    public CategoryUpdateJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblCardId = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnPrevious1 = new RoundedButton("", 35);
        btnPrevious4 = new RoundedButton("", 35);
        btnPrevious5 = new RoundedButton("", 35);
        btnPrevious6 = new RoundedButton("", 35);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(480, 230));

        jPanel1.setBackground(new java.awt.Color(15, 158, 213));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 340));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setBorder(null);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, 35));

        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 200, 35));

        lblId.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Mã loại ");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 56, -1));

        lblCardId.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lblCardId.setForeground(new java.awt.Color(255, 255, 255));
        lblCardId.setText("Tên loại");
        jPanel1.add(lblCardId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 54, -1));

        btnNew.setText("Làm mới");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        btnUpdate.setText("Thêm");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnPrevious1.setBackground(new java.awt.Color(11, 118, 162));
        btnPrevious1.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious1.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious1.setText("<<");
        btnPrevious1.setBorder(null);
        btnPrevious1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious1ActionPerformed(evt);
            }
        });

        btnPrevious4.setBackground(new java.awt.Color(11, 118, 162));
        btnPrevious4.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious4.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious4.setText("<");
        btnPrevious4.setBorder(null);
        btnPrevious4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious4ActionPerformed(evt);
            }
        });

        btnPrevious5.setBackground(new java.awt.Color(11, 118, 162));
        btnPrevious5.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious5.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious5.setText(">>");
        btnPrevious5.setBorder(null);
        btnPrevious5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious5ActionPerformed(evt);
            }
        });

        btnPrevious6.setBackground(new java.awt.Color(11, 118, 162));
        btnPrevious6.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious6.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious6.setText(">");
        btnPrevious6.setBorder(null);
        btnPrevious6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrevious5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrevious4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPrevious5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevious6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevious1ActionPerformed

    private void btnPrevious4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevious4ActionPerformed

    private void btnPrevious5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevious5ActionPerformed

    private void btnPrevious6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevious6ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Category updated = getForm();
        if (updated != null) {
            this.category = updated; // lưu vào biến để lấy sau
            dispose(); // đóng dialog
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CategoryUpdateJDialog dialog = new CategoryUpdateJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPrevious1;
    private javax.swing.JButton btnPrevious4;
    private javax.swing.JButton btnPrevious5;
    private javax.swing.JButton btnPrevious6;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCardId;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
private void init() {
        // Bổ sung thêm nếu cần khởi tạo mặc định
    }

    public void setForm(Category c) {
        this.category = c;
        txtId.setText(String.valueOf(c.getId()));
        txtName.setText(c.getName());
    }

    public Category getForm() {
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            String name = txtName.getText().trim();

            if (name.isBlank()) {
                JOptionPane.showMessageDialog(this, "Tên danh mục không được để trống");
                return null;
            }

            return Category.builder()
                    .Id(id)
                    .name(name)
                    .build();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID không hợp lệ");
            return null;
        }
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

}
