/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fpt.ptcd.ui.update;

import com.fpt.ptcd.util.RoundedButton;
import com.fpt.ptcd.util.XImage;
import com.fpt.ptcd.dao.GroundWorkDAO;
import com.fpt.ptcd.dao.UserDAO;
import com.fpt.ptcd.entity.GroundWork;
import com.fpt.ptcd.entity.User;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class UserUpdateJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HistoryAddJDialog
     */
    public UserUpdateJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        loadGroundWorkToComboBox(); // ✅ QUAN TRỌNG: phải load dữ liệu GroundWork trước khi setForm
        setAvatar(null); // ảnh mặc định
        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Admin", "User"}));
        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Kích hoạt", "Khóa"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnPhoto = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        cboRole = new javax.swing.JComboBox<>();
        lblGroundWork = new javax.swing.JLabel();
        cboGroundWork = new javax.swing.JComboBox<>();
        cboStatus = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(480, 340));

        jPanel1.setBackground(new java.awt.Color(15, 157, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvatar.setText("jLabel1");

        javax.swing.GroupLayout pnPhotoLayout = new javax.swing.GroupLayout(pnPhoto);
        pnPhoto.setLayout(pnPhotoLayout);
        pnPhotoLayout.setHorizontalGroup(
            pnPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhotoLayout.createSequentialGroup()
                .addComponent(lblAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnPhotoLayout.setVerticalGroup(
            pnPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhotoLayout.createSequentialGroup()
                .addComponent(lblAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 190, 190));

        txtId.setBorder(null);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 240, 35));

        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 35));

        lblId.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Mã số");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lblUsername.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Tên người dùng");
        jPanel1.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, -1));

        lblPassword.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Mật khẩu");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 240, 35));

        btnNew.setText("Làm mới");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        btnAdd.setText("Thêm");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblRole.setText("Chức vụ");

        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoàn tất" }));

        lblGroundWork.setText("Cơ sở");

        cboGroundWork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoàn tất" }));

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoàn tất" }));

        lblStatus.setText("Trạng thái");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboGroundWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGroundWork))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGroundWork)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboGroundWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        User user = getForm();
        if (user != null) {
            try {
                userDAO.update(user); // hoặc insert nếu là thêm mới
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUpdateJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserUpdateJDialog dialog = new UserUpdateJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnNew;
    private javax.swing.JComboBox<String> cboGroundWork;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblGroundWork;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnPhoto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    private List<GroundWork> groundWorkList = new ArrayList<>();
    private UserDAO userDAO = new UserDAO();

    public void setForm(User user) {
        txtId.setText(user.getId());
        txtPassword.setText(user.getPassword());
        txtUsername.setText(user.getFullname());
        cboRole.setSelectedItem(user.isRole() ? "Admin" : "User");
        cboStatus.setSelectedItem(user.isEnabled() ? "Kích hoạt" : "Khóa");
        for (int i = 0; i < cboGroundWork.getItemCount(); i++) {
            if (getGroundWorkIdByIndex(i) == user.getGroundWorkId()) {
                cboGroundWork.setSelectedIndex(i);
                break;
            }
        }
        setAvatar(user.getPhoto());
    }

    public User getForm() {
        String id = txtId.getText().trim();
        String password = txtPassword.getText().trim();
        String fullname = txtUsername.getText().trim();

        if (id.isEmpty() || password.isEmpty() || fullname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID, Mật khẩu và Họ tên không được để trống!");
            return null;
        }

        boolean role = cboRole.getSelectedItem().toString().equals("Admin");
        boolean enabled = cboStatus.getSelectedItem().toString().equals("Kích hoạt");
        int groundWorkId = getGroundWorkIdByIndex(cboGroundWork.getSelectedIndex());
        String photo = lblAvatar.getToolTipText();
        if (photo == null || photo.isEmpty()) {
            photo = "default-avatar.jpg";
        }

        return User.builder()
                .id(id)
                .password(password)
                .fullname(fullname)
                .role(role)
                .enabled(enabled)
                .groundWorkId(groundWorkId)
                .photo(photo)
                .build();
    }

    public void clearForm() {
        txtId.setText("");
        txtPassword.setText("");
        txtUsername.setText("");
        cboRole.setSelectedIndex(0);
        cboStatus.setSelectedIndex(0);
        cboGroundWork.setSelectedIndex(0);
        setAvatar(null);
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    private void setAvatar(String fileName) {
        if (fileName == null || fileName.isEmpty()) {
            fileName = "default-avatar.jpg";
        }
        ImageIcon icon = XImage.readScaled(fileName, lblAvatar);
        lblAvatar.setIcon(icon);
        lblAvatar.setToolTipText(fileName);
    }

    private void upload() {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            if (XImage.save(file)) {
                String fileName = file.getName();
                setAvatar(fileName);
            } else {
                JOptionPane.showMessageDialog(this, "Không thể lưu ảnh!");
            }
        }
    }

    private void loadGroundWorkToComboBox() {
        try {
            GroundWorkDAO dao = new GroundWorkDAO();
            groundWorkList = dao.selectAll();
            cboGroundWork.removeAllItems();
            for (GroundWork gw : groundWorkList) {
                cboGroundWork.addItem(gw.getName());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi load danh sách cơ sở: " + e.getMessage());
        }
    }

    private int getGroundWorkIdByIndex(int index) {
        if (index >= 0 && index < groundWorkList.size()) {
            return groundWorkList.get(index).getGroundWorkID();
        }
        return -1;
    }
}
