/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fpt.ptcd.ui.add;

import com.fpt.ptcd.dao.BakeryDAO;
import com.fpt.ptcd.dao.BillDAO;
import com.fpt.ptcd.dao.BillDetailsDAO;
import com.fpt.ptcd.dao.CardDAO;
import com.fpt.ptcd.dao.GroundWorkDAO;
import com.fpt.ptcd.dao.UserDAO;
import com.fpt.ptcd.entity.Bakery;
import com.fpt.ptcd.entity.Bill;
import com.fpt.ptcd.entity.BillDetails;
import com.fpt.ptcd.entity.Card;
import com.fpt.ptcd.entity.GroundWork;
import com.fpt.ptcd.entity.User;
import com.fpt.ptcd.ui.dialog.BakeryJDialog;
import com.fpt.ptcd.util.LookAndFeelUtil;
import com.fpt.ptcd.util.MsgBox;
import com.fpt.ptcd.util.XImage;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author admin
 */
public class BillAddJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HistoryAddJDialog
     */
    public BillAddJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        LookAndFeelUtil.applyFlatLafLight();
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboStatus = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        cboPayment = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblQuanity = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblCardId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        spQuanity = new javax.swing.JSpinner();
        cboCardId = new javax.swing.JComboBox<>();
        dcCheckIn = new com.toedter.calendar.JDateChooser();
        dcCheckOut = new com.toedter.calendar.JDateChooser();
        lblBegin = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblDatHang1 = new javax.swing.JLabel();
        lblNhanVien1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPhoto = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        slDiscount = new javax.swing.JSlider();
        lblPercentDiscount = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtFianlPrice = new javax.swing.JTextField();
        btnCancle = new javax.swing.JButton();
        cboGroundWork = new javax.swing.JComboBox<>();
        lblPayment1 = new javax.swing.JLabel();
        cboUsers = new javax.swing.JComboBox<>();
        lblPayment2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(480, 340));

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã thanh toán", "Chưa thanh toán" }));
        cboStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        lblStatus.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblStatus.setText("Trạng thái đơn hàng");

        lblPayment.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblPayment.setText("Loại hình thanh toán");

        cboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Thẻ ngân hàng" }));
        cboPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        btnAdd.setText("Thêm");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(59, 125, 35));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuanity.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblQuanity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanity.setText("Số lượng");
        jPanel1.add(lblQuanity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 76, -1));

        lblId.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Mã phiếu");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        lblCardId.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblCardId.setForeground(new java.awt.Color(255, 255, 255));
        lblCardId.setText("Mã thẻ");
        jPanel1.add(lblCardId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 200, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 35));
        jPanel1.add(spQuanity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 33));

        cboCardId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCardId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCardIdActionPerformed(evt);
            }
        });
        jPanel1.add(cboCardId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 200, 35));
        jPanel1.add(dcCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, 35));
        jPanel1.add(dcCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 35));

        lblBegin.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblBegin.setForeground(new java.awt.Color(255, 255, 255));
        lblBegin.setText("Thời điểm tạo");
        jPanel1.add(lblBegin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblEnd.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblEnd.setForeground(new java.awt.Color(255, 255, 255));
        lblEnd.setText("Thời điểm thanh toán");
        jPanel1.add(lblEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        lblDatHang1.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblDatHang1.setForeground(new java.awt.Color(255, 255, 255));
        lblDatHang1.setText("Thành tiền");
        jPanel1.add(lblDatHang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        lblNhanVien1.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblNhanVien1.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanVien1.setText("Đơn giá");
        jPanel1.add(lblNhanVien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 51, -1));

        btnPhoto.setText("Chọn sản phẩm");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 210, 200));

        lblPercentDiscount.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblPercentDiscount.setText("100%");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(slDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPercentDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(slDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(lblPercentDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 200, 30));

        lblDiscount.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lblDiscount.setText("Giảm giá");
        jPanel1.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 35));

        txtName.setText("Tên sản phẩm");
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 210, 35));
        jPanel1.add(txtFianlPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, 35));

        btnCancle.setText("Hủy");
        btnCancle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        cboGroundWork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        lblPayment1.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblPayment1.setText("Cơ sở");

        cboUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        lblPayment2.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        lblPayment2.setText("Người thực hiện");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboGroundWork, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPayment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPayment2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPayment1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboGroundWork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPayment)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPayment2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCardIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCardIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCardIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Bill bill = getBill();
        List<BillDetails> details = getBillDetails();
            confirmed = true;
            dispose();

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        this.getBakeryInfo();
    }//GEN-LAST:event_btnPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillAddJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillAddJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillAddJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillAddJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillAddJDialog dialog = new BillAddJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JComboBox<String> cboCardId;
    private javax.swing.JComboBox<String> cboGroundWork;
    private javax.swing.JComboBox<String> cboPayment;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JComboBox<String> cboUsers;
    private com.toedter.calendar.JDateChooser dcCheckIn;
    private com.toedter.calendar.JDateChooser dcCheckOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBegin;
    private javax.swing.JLabel lblCardId;
    private javax.swing.JLabel lblDatHang1;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNhanVien1;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPayment1;
    private javax.swing.JLabel lblPayment2;
    private javax.swing.JLabel lblPercentDiscount;
    private javax.swing.JLabel lblQuanity;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JSlider slDiscount;
    private javax.swing.JSpinner spQuanity;
    private javax.swing.JTextField txtFianlPrice;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
    // ======================== DAO ==========================
    private final BillDAO billDAO = new BillDAO();
    private final BillDetailsDAO billDetailDAO = new BillDetailsDAO();
    private final BakeryDAO bakeryDAO = new BakeryDAO();
    private final UserDAO userDAO = new UserDAO();
    private final CardDAO cardDAO = new CardDAO();
    private final GroundWorkDAO groundWorkDAO = new GroundWorkDAO();

    // ======================== STATE ==========================
    private boolean confirmed = false;
    private int selectedBakeryId = -1;

    // ======================== KHỞI TẠO ==========================
    private void init() {
        setTitle("Thêm hóa đơn mới");
        setLocationRelativeTo(null);
        fillComboBoxes();
        slDiscount.setValue(0);
        setPhoto(null);
        dcCheckIn.setDate(new Date());
    }

    // ======================== NẠP COMBOBOX ==========================
    private void fillComboBoxes() {
        // ======== Nạp comboBox người dùng ========
        cboUsers.removeAllItems();
        for (User u : userDAO.selectAll()) {
            cboUsers.addItem(u.getId()); // Combo hiển thị ID user
        }

        // ======== Nạp comboBox thẻ ========
        cboCardId.removeAllItems();
        for (Card c : cardDAO.selectAll()) {
            cboCardId.addItem(String.valueOf(c.getId())); // Hiển thị ID thẻ
        }

        // ======== Nạp comboBox cơ sở ========
        cboGroundWork.removeAllItems();
        for (GroundWork g : groundWorkDAO.selectAll()) {
            cboGroundWork.addItem(String.valueOf(g.getGroundWorkID())); // Hiển thị ID cơ sở
        }

        // ======== Thiết lập mặc định cho comboBox trạng thái và thanh toán ========
        cboStatus.removeAllItems();
        cboStatus.addItem("Chưa thanh toán");
        cboStatus.addItem("Đã thanh toán");

        cboPayment.removeAllItems();
        cboPayment.addItem("Khác");
        cboPayment.addItem("Tiền mặt");
        cboPayment.addItem("Chuyển khoản");
    }

    // ======================== LẤY DỮ LIỆU BILL ==========================
    public Bill getBill() {
        try {
            return Bill.builder()
                    .id(Integer.parseInt(txtId.getText().trim()))
                    .username(cboUsers.getSelectedItem().toString())
                    .cardId(Integer.parseInt(cboCardId.getSelectedItem().toString()))
                    .groundWorkId(Integer.parseInt(cboGroundWork.getSelectedItem().toString()))
                    .paymentMethod(cboPayment.getSelectedIndex())
                    .status(cboStatus.getSelectedIndex() == 1)
                    .checkIn(dcCheckIn.getDate())
                    .checkOut(dcCheckOut.getDate())
                    .build();
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi dữ liệu hóa đơn: " + e.getMessage());
            return null;
        }
    }
    // ======================== LẤY DỮ LIỆU BILLDETAIL ==========================

    public List<BillDetails> getBillDetails() {
        try {
            if (selectedBakeryId == -1) {
                MsgBox.alert(this, "Chưa chọn sản phẩm bánh!");
                return null;
            }

            BillDetails detail = BillDetails.builder()
                    .billId(Integer.parseInt(txtId.getText().trim()))
                    .bakeryId(selectedBakeryId)
                    .productName(txtName.getText())
                    .unit("cái")
                    .quantity(((Integer) spQuanity.getValue()).doubleValue())
                    .unitPrice(Double.parseDouble(txtPrice.getText()))
                    .discount(slDiscount.getValue() / 100.0)
                    .finalPrice(Double.parseDouble(txtFianlPrice.getText()))
                    .build();

            return List.of(detail);
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi dữ liệu chi tiết hóa đơn: " + e.getMessage());
            return null;
        }
    }

    // ======================== HIỂN THỊ SẢN PHẨM ĐƯỢC CHỌN ==========================
    public void setBakeryInfo(Bakery b) {
        if (b == null) {
            return;
        }

        selectedBakeryId = b.getId();
        txtName.setText(b.getName());
        txtPrice.setText(String.valueOf(b.getUnitPrice()));
        slDiscount.setValue((int) (b.getDiscount() * 100));
        spQuanity.setValue(1);

        updateFinalPrice();
        setPhoto(b.getPhoto());
    }

    // ======================== MỞ DIALOG CHỌN BÁNH ==========================
    public void getBakeryInfo() {
        BakeryJDialog dialog = new BakeryJDialog(null, true);
        dialog.setTitle("Chọn sản phẩm bánh");
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        Object[] selected = dialog.getSelectedBakery();
        if (selected != null) {
            txtName.setText(String.valueOf(selected[0]));
            txtPrice.setText(String.valueOf(selected[1]));
            txtFianlPrice.setText(String.valueOf(selected[2]));
            selectedBakeryId = (Integer) selected[4];

            String imageFileName = (String) selected[3];
            if (imageFileName != null && !imageFileName.isBlank()) {
                btnPhoto.setIcon(XImage.readScaled(imageFileName, btnPhoto));
                btnPhoto.putClientProperty("fileName", imageFileName);
            }

            if (selected.length >= 5) {
                selectedBakeryId = (Integer) selected[4]; // ✅ chỗ này quan trọng
            } else {
                selectedBakeryId = -1;
            }

            System.out.println("✅ Selected Bakery ID = " + selectedBakeryId); // debug log
        }
    }

    // ======================== CẬP NHẬT ẢNH ==========================
    private void setPhoto(String fileName) {
        if (fileName != null) {
            ImageIcon icon = XImage.readScaled(fileName, btnPhoto);
            btnPhoto.setIcon(icon);
            btnPhoto.putClientProperty("fileName", fileName);
        } else {
            btnPhoto.setIcon(null);
            btnPhoto.putClientProperty("fileName", null);
        }
    }

    // ======================== CẬP NHẬT THÀNH TIỀN ==========================
    private void updateFinalPrice() {
        try {
            double price = Double.parseDouble(txtPrice.getText());
            int quantity = (int) spQuanity.getValue();
            double discount = slDiscount.getValue() / 100.0;
            double finalPrice = price * quantity * (1 - discount);
            txtFianlPrice.setText(String.format("%.2f", finalPrice));
        } catch (Exception e) {
            txtFianlPrice.setText("0");
        }
    }

    // ======================== XÓA DỮ LIỆU FORM ==========================
    public void clearForm() {
        txtId.setText("");
        cboUsers.setSelectedIndex(0);
        cboCardId.setSelectedIndex(0);
        cboGroundWork.setSelectedIndex(0);
        cboPayment.setSelectedIndex(0);
        cboStatus.setSelectedIndex(0);
        dcCheckIn.setDate(new Date());
        dcCheckOut.setDate(null);

        selectedBakeryId = -1;
        txtName.setText("");
        txtPrice.setText("");
        txtFianlPrice.setText("");
        slDiscount.setValue(0);
        spQuanity.setValue(0);
        setPhoto(null);
    }

    // ======================== ĐỔ DỮ LIỆU FORM (CHỈ DÙNG NẾU UPDATE) ==========================
    public void setForm(Bill bill, List<BillDetails> details) {
        // ======== Đổ dữ liệu Bill =========
        txtId.setText(String.valueOf(bill.getId()));
        cboUsers.setSelectedItem(bill.getUsername());
        cboCardId.setSelectedItem(String.valueOf(bill.getCardId()));
        cboGroundWork.setSelectedItem(String.valueOf(bill.getGroundWorkId()));
        cboPayment.setSelectedIndex(bill.getPaymentMethod());
        cboStatus.setSelectedIndex(bill.getStatus() ? 1 : 0);
        dcCheckIn.setDate(bill.getCheckIn());
        dcCheckOut.setDate(bill.getCheckOut());

        // ======== Đổ dữ liệu chi tiết Bill (chỉ lấy dòng đầu vì 1 sản phẩm) =========
        if (!details.isEmpty()) {
            BillDetails d = details.get(0);
            selectedBakeryId = d.getBakeryId();

            txtName.setText(d.getProductName());
            txtPrice.setText(String.valueOf(d.getUnitPrice()));
            slDiscount.setValue((int) (d.getDiscount() * 100));
            spQuanity.setValue((double) d.getQuantity());
            txtFianlPrice.setText(String.format("%.2f", d.getFinalPrice()));

            // ======== Truy vấn lại ảnh từ BakeryDAO (nếu có) =========
            Bakery b = bakeryDAO.selectByID(d.getBakeryId());
            if (b != null && b.getPhoto() != null && !b.getPhoto().isBlank()) {
                setPhoto(b.getPhoto()); // XImage sẽ xử lý hiển thị ảnh
            } else {
                setPhoto(null); // reset nếu không có ảnh
            }
        }
    }

    // ======================== LẤY NÚT THÊM ==========================
    public boolean isConfirmed() {
        return confirmed;
    }

    private boolean validateForm() {
        if (txtId.getText().trim().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập mã hóa đơn.");
            txtId.requestFocus();
            return false;
        }

        try {
            Integer.parseInt(txtId.getText().trim());
        } catch (NumberFormatException e) {
            MsgBox.alert(this, "Mã hóa đơn phải là số.");
            txtId.requestFocus();
            return false;
        }

        if (cboUsers.getSelectedItem() == null) {
            MsgBox.alert(this, "Vui lòng chọn người dùng.");
            cboUsers.requestFocus();
            return false;
        }

        if (cboCardId.getSelectedItem() == null) {
            MsgBox.alert(this, "Vui lòng chọn thẻ.");
            cboCardId.requestFocus();
            return false;
        }

        if (cboGroundWork.getSelectedItem() == null) {
            MsgBox.alert(this, "Vui lòng chọn cơ sở.");
            cboGroundWork.requestFocus();
            return false;
        }

        if (dcCheckIn.getDate() == null) {
            MsgBox.alert(this, "Vui lòng chọn thời điểm Check In.");
            dcCheckIn.requestFocus();
            return false;
        }

        if (spQuanity.getValue().equals(0)) {
            MsgBox.alert(this, "Số lượng bánh phải lớn hơn 0.");
            spQuanity.requestFocus();
            return false;
        }

        if (selectedBakeryId == -1) {
            MsgBox.alert(this, "Bạn chưa chọn sản phẩm bánh.");
            return false;
        }

        return true;
    }

}
