/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.fpt.ptcd.ui.add;

import com.fpt.ptcd.dao.CardDAO;
import com.fpt.ptcd.entity.Card;
import com.fpt.ptcd.ui.panel.CardManagerJPannel;
import com.fpt.ptcd.util.RoundedButton;
import java.awt.Color;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class CardAddJDialog extends javax.swing.JDialog {

    private CardManagerJPannel cardPanel;
    private final CardDAO dao = new CardDAO();
    private List<Card> cardList = new ArrayList<>();
    private int currentIndex = 0;

  


    /**
     * Creates new form HistoryAddJDialog
     */
    public CardAddJDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblCardId = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();
        btnNew = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnPrevious1 = new RoundedButton("", 35);
        btnPrevious4 = new RoundedButton("", 35);
        btnPrevious5 = new RoundedButton("", 35);
        btnPrevious6 = new RoundedButton("", 35);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(480, 340));

        jPanel1.setBackground(new java.awt.Color(59, 125, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 340));

        txtId.setBorder(null);

        lblId.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("Mã loại ");

        lblCardId.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        lblCardId.setForeground(new java.awt.Color(255, 255, 255));
        lblCardId.setText("Tên loại");

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCardId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblCardId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cboStatus))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        btnNew.setText("Làm mới");
        btnNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        btnAdd.setText("Thêm");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPrevious1.setBackground(new java.awt.Color(61, 123, 35));
        btnPrevious1.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious1.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious1.setText("<<");
        btnPrevious1.setBorder(null);
        btnPrevious1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious1ActionPerformed(evt);
            }
        });

        btnPrevious4.setBackground(new java.awt.Color(61, 123, 35));
        btnPrevious4.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious4.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious4.setText("<");
        btnPrevious4.setBorder(null);
        btnPrevious4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious4ActionPerformed(evt);
            }
        });

        btnPrevious5.setBackground(new java.awt.Color(61, 123, 35));
        btnPrevious5.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious5.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious5.setText(">>");
        btnPrevious5.setBorder(null);
        btnPrevious5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious5ActionPerformed(evt);
            }
        });

        btnPrevious6.setBackground(new java.awt.Color(61, 123, 35));
        btnPrevious6.setFont(new java.awt.Font("Bahnschrift", 1, 22)); // NOI18N
        btnPrevious6.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious6.setText(">");
        btnPrevious6.setBorder(null);
        btnPrevious6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrevious6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPrevious6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrevious6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevious6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrevious5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrevious4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPrevious5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevious6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious1ActionPerformed
        moveFirst();
    }//GEN-LAST:event_btnPrevious1ActionPerformed

    private void btnPrevious4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious4ActionPerformed
        movePrevious();
    }//GEN-LAST:event_btnPrevious4ActionPerformed

    private void btnPrevious5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious5ActionPerformed
        moveLast();
    }//GEN-LAST:event_btnPrevious5ActionPerformed

    private void btnPrevious6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevious6ActionPerformed
        moveNext();
    }//GEN-LAST:event_btnPrevious6ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        insertCard();
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(CardAddJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

   java.awt.EventQueue.invokeLater(() -> {
    CardAddJDialog dialog = new CardAddJDialog(new JFrame(), true); 
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
        }
    });
    dialog.setVisible(true);
});

}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPrevious1;
    private javax.swing.JButton btnPrevious4;
    private javax.swing.JButton btnPrevious5;
    private javax.swing.JButton btnPrevious6;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCardId;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
private void init() {
    cboStatus.removeAllItems();
    cboStatus.addItem("OPERATING");
    cboStatus.addItem("LOST");
    cboStatus.addItem("ERROR");
    cboStatus.addItem("UNKNOWN");
}



    private void insertCard() {
    try {
        int id = Integer.parseInt(txtId.getText().trim());

        // Kiểm tra trùng ID
        if (dao.selectByID(id) != null) {
            JOptionPane.showMessageDialog(this, "ID đã tồn tại. Vui lòng nhập ID khác.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tạo card mới
        Card card = getForm();
        dao.insert(card);

        JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
        if (cardPanel != null) {
            cardPanel.fillTable();  // Gọi JPanel reload bảng
        }
        this.dispose(); // Đóng dialog
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID phải là số nguyên.", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
}


    private boolean checkDuplicateId(int id) {
        return dao.selectByID(id) != null;
    }

    private Card getForm() {
        Card card = new Card();
        card.setId(Integer.parseInt(txtId.getText().trim()));
        card.setStatus(cboStatus.getSelectedIndex());
        return card;
    }

    public void setForm(Card card) {
        if (card == null) return;
        txtId.setText(String.valueOf(card.getId()));
        cboStatus.setSelectedIndex(card.getStatus());
    }

    private void clearForm() {
        txtId.setText("");
        cboStatus.setSelectedIndex(0);
        txtId.requestFocus();
    }

    private void moveFirst() {
        if (cardList.isEmpty()) return;
        currentIndex = 0;
        setForm(cardList.get(currentIndex));
    }

    private void movePrevious() {
        if (cardList.isEmpty()) return;
        currentIndex = (currentIndex <= 0) ? cardList.size() - 1 : currentIndex - 1;
        setForm(cardList.get(currentIndex));
    }

    private void moveNext() {
        if (cardList.isEmpty()) return;
        currentIndex = (currentIndex >= cardList.size() - 1) ? 0 : currentIndex + 1;
        setForm(cardList.get(currentIndex));
    }

    private void moveLast() {
        if (cardList.isEmpty()) return;
        currentIndex = cardList.size() - 1;
        setForm(cardList.get(currentIndex));
    }

}
