/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.cafe.ui;

import java.awt.Component;
import java.awt.Frame;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import poly.cafe.dao.BillDAO;
import poly.cafe.dao.CategoryDAO;
import poly.cafe.entity.Bill;
import poly.cafe.entity.Drink;
import poly.cafe.util.MsgBox;
import poly.cafe.util.TimeRange;
import poly.cafe.util.XDate;
import poly.cafe.util.XImage;

/**
 *
 * @author admin
 */
public class BillManagerJDialog extends javax.swing.JDialog {

    BillDAO daoBill = new BillDAO();
    int row = -1; // Hàng được chọn trên bảng

// Constructor phụ: Để đảm bảo tương thích với lệnh gọi cũ
    public BillManagerJDialog(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
        init();

    }

    void init() {
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ PHIẾU BÁN HÀNG");
        cboTimeRanges.addActionListener(e -> selectTimeRange());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblBegin = new javax.swing.JLabel();
        txtBegin = new javax.swing.JTextField();
        lblEnd = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();
        cboTimeRanges = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        btnSelectAll = new javax.swing.JButton();
        btnNoSelectAll = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblCardId = new javax.swing.JLabel();
        txtCardId2 = new javax.swing.JTextField();
        txtId2 = new javax.swing.JTextField();
        lblBegin2 = new javax.swing.JLabel();
        txtBegin2 = new javax.swing.JTextField();
        lblEnd2 = new javax.swing.JLabel();
        txtEnd2 = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBill = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnPrevioust = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        rdnServicing = new javax.swing.JRadioButton();
        rdnCanceled = new javax.swing.JRadioButton();
        rdnCompleted = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản lý phiếu");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblBegin.setText("Từ ngày:");

        txtBegin.setText("01/01/2025");

        lblEnd.setText("Đến ngày:");

        txtEnd.setText("01/01/2026");

        btnFilter.setText("Lọc");

        cboTimeRanges.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm nay ", "Tuần này", "Tháng này", "Quý này", "Năm nay" }));

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Thẻ số ", "Thời điểm tạo", "Thời điểm thanh toán", "Trạng thái", "Gmail", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBill);

        btnSelectAll.setText("Chọn tất cả ");
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAllActionPerformed(evt);
            }
        });

        btnNoSelectAll.setText("bỏ chọn tất cả");
        btnNoSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoSelectAllActionPerformed(evt);
            }
        });

        Delete.setText("xóa các mục chọn");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblBegin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEnd)
                .addGap(18, 18, 18)
                .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboTimeRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSelectAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNoSelectAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Delete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBegin)
                    .addComponent(txtBegin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnd)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter)
                    .addComponent(cboTimeRanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectAll)
                    .addComponent(btnNoSelectAll)
                    .addComponent(Delete))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DANH SÁCH", jPanel2);

        lblId.setText("Mã phiếu");

        lblCardId.setText("Thẻ số");

        txtCardId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardId2ActionPerformed(evt);
            }
        });

        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });

        lblBegin2.setText("Thời điểm tạo");

        txtBegin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBegin2ActionPerformed(evt);
            }
        });

        lblEnd2.setText("Thời điểm thanh toán");

        txtEnd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnd2ActionPerformed(evt);
            }
        });

        lblStatus.setText("Trạng thái");

        jLabel9.setText("Người tạo");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        listBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Đồ uống", "Đơn giá", "Giảm giá", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(listBill);

        btnCreate.setText("Tạo mới");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhập");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNew.setText("Nhập mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnLast.setText("<");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnPrevioust.setText("<<");
        btnPrevioust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevioustActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnFirst.setText(">");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnServicing);
        rdnServicing.setText("Servicing");
        rdnServicing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnServicingActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnCanceled);
        rdnCanceled.setText("Canceled");
        rdnCanceled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnCanceledActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnCompleted);
        rdnCompleted.setText("Completed");
        rdnCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnCompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtBegin2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                        .addComponent(txtCardId2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblBegin2)
                                    .addComponent(lblStatus))
                                .addGap(64, 64, 64))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(rdnServicing)
                                .addGap(9, 9, 9)
                                .addComponent(rdnCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdnCanceled)
                                .addGap(86, 86, 86)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCardId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtId2)
                                .addComponent(txtEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEnd2)
                                .addComponent(jLabel9))
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCreate)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnNew)
                                .addGap(219, 219, 219)
                                .addComponent(btnLast)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrevioust)
                                .addGap(18, 18, 18)
                                .addComponent(btnNext)
                                .addGap(18, 18, 18)
                                .addComponent(btnFirst))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCardId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBegin2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBegin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCardId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdnServicing)
                            .addComponent(rdnCompleted)
                            .addComponent(rdnCanceled)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnNew)
                    .addComponent(btnLast)
                    .addComponent(btnPrevioust)
                    .addComponent(btnNext)
                    .addComponent(btnFirst))
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("BIỄU MẪU", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAllActionPerformed
        // TODO add your handling code here:
        btnSelectAll();
    }//GEN-LAST:event_btnSelectAllActionPerformed

    private void btnNoSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoSelectAllActionPerformed
        // TODO add your handling code here:
        btnUnselectAll();
    }//GEN-LAST:event_btnNoSelectAllActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        btnDeleteSelected();
    }//GEN-LAST:event_DeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        insertBill();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteBill();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateBill();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtCardId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardId2ActionPerformed
        getForm();
    }//GEN-LAST:event_txtCardId2ActionPerformed

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        getForm();
    }//GEN-LAST:event_txtId2ActionPerformed

    private void txtBegin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBegin2ActionPerformed
        getForm();
    }//GEN-LAST:event_txtBegin2ActionPerformed

    private void txtEnd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnd2ActionPerformed
        getForm();
    }//GEN-LAST:event_txtEnd2ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        getForm();
    }//GEN-LAST:event_txtUserActionPerformed

    private void rdnServicingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnServicingActionPerformed

    }//GEN-LAST:event_rdnServicingActionPerformed

    private void rdnCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnCompletedActionPerformed

    }//GEN-LAST:event_rdnCompletedActionPerformed

    private void rdnCanceledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnCanceledActionPerformed

    }//GEN-LAST:event_rdnCanceledActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed

    }//GEN-LAST:event_btnLastActionPerformed

    private void btnPrevioustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevioustActionPerformed

    }//GEN-LAST:event_btnPrevioustActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed

    }//GEN-LAST:event_btnFirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillManagerJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BillManagerJDialog dialog = new BillManagerJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNoSelectAll;
    private javax.swing.JButton btnPrevioust;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboTimeRanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBegin;
    private javax.swing.JLabel lblBegin2;
    private javax.swing.JLabel lblCardId;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblEnd2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable listBill;
    private javax.swing.JRadioButton rdnCanceled;
    private javax.swing.JRadioButton rdnCompleted;
    private javax.swing.JRadioButton rdnServicing;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtBegin;
    private javax.swing.JTextField txtBegin2;
    private javax.swing.JTextField txtCardId2;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtEnd2;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    private boolean validateForm() {
        // Mã phiếu không để trống
        if (txtCardId2.getText().trim().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập mã phiếu.");
            txtCardId2.requestFocus();
            return false;
        }

        // Thẻ số: không để trống, là số nguyên dương
        String cardId = txtId2.getText().trim();
        if (cardId.isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập thẻ số.");
            txtId2.requestFocus();
            return false;
        }
        if (!cardId.matches("\\d+")) {
            MsgBox.alert(this, "Thẻ số phải là số nguyên dương.");
            txtId2.requestFocus();
            return false;
        }

        // Người dùng: không để trống, độ dài tối thiểu 3 ký tự
        String user = txtUser.getText().trim();
        if (user.isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập tên người dùng.");
            txtUser.requestFocus();
            return false;
        }
        if (user.length() < 3) {
            MsgBox.alert(this, "Tên người dùng phải từ 3 ký tự trở lên.");
            txtUser.requestFocus();
            return false;
        }

        // Trạng thái: phải chọn 1 trong 3
        if (!rdnServicing.isSelected() && !rdnCompleted.isSelected() && !rdnCanceled.isSelected()) {
            MsgBox.alert(this, "Vui lòng chọn trạng thái.");
            return false;
        }

        return true;
    }

    private boolean validateDate() {
        String beginText = txtBegin.getText().trim();
        String endText = txtEnd.getText().trim();

        if (beginText.isEmpty() || endText.isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập đầy đủ cả hai ngày.");
            return false;
        }

        try {
            Date begin = XDate.parse(beginText, "dd/MM/yyyy");
            Date end = XDate.parse(endText, "dd/MM/yyyy");

            if (begin.after(end)) {
                MsgBox.alert(this, "'Từ ngày' phải trước hoặc bằng 'Đến ngày'.");
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Ngày nhập không đúng định dạng (dd/MM/yyyy).");
            return false;
        }

        return true;
    }

    void fillTableBill() {
        DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
        model.setRowCount(0);

        try {
            Date begin = XDate.parse(txtBegin.getText(), "dd/MM/yyyy");
            Date end = XDate.parse(txtEnd.getText(), "dd/MM/yyyy");

            Calendar cal = Calendar.getInstance();
            cal.setTime(end);
            cal.set(Calendar.HOUR_OF_DAY, 23);
            cal.set(Calendar.MINUTE, 59);
            cal.set(Calendar.SECOND, 59);
            cal.set(Calendar.MILLISECOND, 999);
            end = cal.getTime();

            List<Bill> list = daoBill.findByTimeRange(begin, end);
            for (Bill cd : list) {
                Object[] row = {
                    cd.getId(), cd.getCardId(),
                    XDate.format(cd.getCheckin(), "dd/MM/yyyy"),
                    XDate.format(cd.getCheckout(), "dd/MM/yyyy"),
                    cd.getStatus(), cd.getUsername(), false // cột checkbox
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }

        autoResizeColumnWidth(tblBill);
    }

    public void autoResizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50;
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 10, width);
            }

            TableCellRenderer headerRenderer = table.getTableHeader().getDefaultRenderer();
            Component headerComp = headerRenderer.getTableCellRendererComponent(
                    table, table.getColumnName(column), false, false, -1, column);
            width = Math.max(headerComp.getPreferredSize().width + 10, width);

            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    public void selectTimeRange() {
        TimeRange range;
        switch (cboTimeRanges.getSelectedIndex()) {
            case 0 ->
                range = TimeRange.today();
            case 1 ->
                range = TimeRange.thisWeek();
            case 2 ->
                range = TimeRange.thisMonth();
            case 3 ->
                range = TimeRange.thisQuarter();
            case 4 ->
                range = TimeRange.thisYear();
            default ->
                range = TimeRange.today();
        }

        txtBegin.setText(XDate.format(range.getBegin(), "dd/MM/yyyy"));
        txtEnd.setText(XDate.format(range.getEnd(), "dd/MM/yyyy"));
        this.fillTableBill();
    }

    void btnSelectAll() {
        DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(true, i, 6);
        }
    }

    void btnUnselectAll() {
        DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(false, i, 6);
        }
    }

    void btnDeleteSelected() {
        DefaultTableModel model = (DefaultTableModel) tblBill.getModel();
        try {
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                Boolean selected = (Boolean) model.getValueAt(i, 6);
                if (Boolean.TRUE.equals(selected)) {
                    Long id = (Long) model.getValueAt(i, 0);
                    daoBill.delete(id);
                    model.removeRow(i);
                }
            }
            MsgBox.alert(this, "Xóa các mục chọn thành công!");
            fillTableBill();
        } catch (Exception e) {
            MsgBox.alert(this, "Xóa các mục chọn thất bại!");
        }
    }

    void clearForm() {
        txtBegin2.setText("");
        txtEnd2.setText("");
        txtCardId2.setText("");
        txtId2.setText("");
        txtUser.setText("");
        rdnServicing.setSelected(false);
        rdnCompleted.setSelected(false);
        rdnCanceled.setSelected(false);
    }

    private void updateBill() {
        try {
            Long id = Long.valueOf(txtCardId2.getText());
            String cardId = txtId2.getText();
            String user = txtUser.getText();
            Date checkin = XDate.parse(txtBegin2.getText(), "dd/MM/yyyy");
            Date checkout = XDate.parse(txtEnd2.getText(), "dd/MM/yyyy");
            String status = getTrangThai();

            Bill bill = new Bill(id, cardId, checkin, checkout, status, user);
            daoBill.update(bill);
            MsgBox.alert(this, "Cập nhật phiếu thành công!");
            fillTableBill();
        } catch (NumberFormatException e) {
            MsgBox.alert(this, "Cập nhật phiếu thất bại!");
        }
    }

    private void insertBill() {
        try {
            Long id = Long.valueOf(txtCardId2.getText());
            String cardId = txtId2.getText();
            String user = txtUser.getText();
            Date checkin = XDate.parse(txtBegin2.getText(), "dd/MM/yyyy");
            Date checkout = XDate.parse(txtEnd2.getText(), "dd/MM/yyyy");

            // Trạng thái mặc định
            String status = "Servicing"; // hoặc Completed/Canceled tùy bạn

            Bill bill = new Bill(id, cardId, checkin, checkout, status, user);
            daoBill.insert(bill);
            MsgBox.alert(this, "Thêm phiếu mới thành công!");
            fillTableBill();
            clearForm();
        } catch (Exception e) {
            e.printStackTrace(); // in lỗi cụ thể
            MsgBox.alert(this, "Thêm phiếu mới thất bại!");
        }
    }

    private String getTrangThai() {
        if (rdnServicing.isSelected()) {
            return "Servicing";
        }
        if (rdnCompleted.isSelected()) {
            return "Completed";
        }
        if (rdnCanceled.isSelected()) {
            return "Canceled";
        }
        return "";
    }

    private void deleteBill() {
        try {
            Long id = Long.valueOf(txtCardId2.getText());
            daoBill.delete(id);
            MsgBox.alert(this, "Xóa phiếu thành công!");
            fillTableBill();
            clearForm();
        } catch (NumberFormatException e) {
            MsgBox.alert(this, "Xóa phiếu thất bại!");
        }
    }

    private Bill getForm() {
        try {
            String idText = txtCardId2.getText().trim();
            String cardId = txtId2.getText().trim();
            String user = txtUser.getText().trim();
            String checkinText = txtBegin2.getText().trim();
            String checkoutText = txtEnd2.getText().trim();

            System.out.println("DEBUG:");
            System.out.println("ID: " + idText);
            System.out.println("Card ID: " + cardId);
            System.out.println("User: " + user);
            System.out.println("Checkin: " + checkinText);
            System.out.println("Checkout: " + checkoutText);

            // Chuyển dữ liệu
            Long id = Long.valueOf(idText);
            Date checkin = XDate.parse(checkinText, "dd/MM/yyyy");
            Date checkout = XDate.parse(checkoutText, "dd/MM/yyyy");

            // Trạng thái mặc định khi không có nút chọn
            String status = "Servicing"; // hoặc "Completed", "Canceled" nếu bạn muốn khác

            return new Bill(id, cardId, checkin, checkout, status, user);

        } catch (Exception e) {
            e.printStackTrace(); // để thấy lỗi thực tế
            MsgBox.alert(this, "Lỗi lấy dữ liệu từ form. Vui lòng kiểm tra lại định dạng và dữ liệu nhập.");
            return null;
        }
    }

}
